// <auto-generated />
using System;
using HomeRecall.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeRecall.Migrations
{
    [DbContext(typeof(BackupContext))]
    [Migration("20260214165909_AddMqttExclusionList")]
    partial class AddMqttExclusionList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HomeRecall.Persistence.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoBackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupStartHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastScanDeviceTypes")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastScanIpEndSuffix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastScanIpStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCountToKeep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDaysToKeep")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MqttAutoAdd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MqttEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MqttExcludedDeviceTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MqttHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("MqttPasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("MqttPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MqttUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseRelativeTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoBackupEnabled = false,
                            BackupIntervalHours = 24,
                            BackupStartHour = 3,
                            LastScanIpEndSuffix = 254,
                            MaxCountToKeep = 10,
                            MaxDaysToKeep = 30,
                            MqttAutoAdd = false,
                            MqttEnabled = false,
                            MqttExcludedDeviceTypes = "",
                            MqttPort = 1883,
                            RetentionMode = 0,
                            UseRelativeTime = true
                        });
                });

            modelBuilder.Entity("HomeRecall.Persistence.Entities.Backup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BackupSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha1Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("HomeRecall.Persistence.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AutoBackupOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentFirmwareVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAutoBackupAttempt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBackup")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("HomeRecall.Persistence.Entities.Backup", b =>
                {
                    b.HasOne("HomeRecall.Persistence.Entities.Device", "Device")
                        .WithMany("Backups")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HomeRecall.Persistence.Entities.Device", b =>
                {
                    b.Navigation("Backups");
                });
#pragma warning restore 612, 618
        }
    }
}
