// <auto-generated />
using System;
using HomeRecall;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

using HomeRecall.Persistence;

namespace HomeRecall.Migrations
{
    [DbContext(typeof(BackupContext))]
    [Migration("20260206183637_AddHostnameAndMacAddress")]
    partial class AddHostnameAndMacAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HomeRecall.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoBackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupStartHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastScanDeviceTypes")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastScanIpEndSuffix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastScanIpStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCountToKeep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDaysToKeep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseRelativeTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoBackupEnabled = false,
                            BackupIntervalHours = 24,
                            BackupStartHour = 3,
                            LastScanIpEndSuffix = 254,
                            MaxCountToKeep = 10,
                            MaxDaysToKeep = 30,
                            RetentionMode = 0,
                            UseRelativeTime = true
                        });
                });

            modelBuilder.Entity("HomeRecall.Backup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha1Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("HomeRecall.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AutoBackupOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentFirmwareVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAutoBackupAttempt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBackup")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("HomeRecall.Backup", b =>
                {
                    b.HasOne("HomeRecall.Device", "Device")
                        .WithMany("Backups")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HomeRecall.Device", b =>
                {
                    b.Navigation("Backups");
                });
#pragma warning restore 612, 618
        }
    }
}
